language: cpp
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
    - gcc-4.8

before_install:
# install the dependencies
   - mkdir air_installer_tmp && cd air_installer_tmp
   - wget https://github.com/kwikius/air_installer/archive/install_test.zip
   - unzip install_test.zip
   - cd air_installer-install_test
   - make clean && make CXX="g++-4.8"
   - mkdir $HOME/ap_lib
   - mkdir $HOME/ap_bin
   - make execute
   - compiler = $HOME/ap_bin/gcc-arm-none-eabi-5_2-2015q4
   - cd $HOME/ap_lib/quantracker && make osd_libs
   
script:  $HOME/ap_bin/gcc-arm-none-eabi-5_2-2015q4/bin/arm-none-eabi-g++ --version
