language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - ccache
    - g++-4.8
    - gcc-4.8

install:
   - mkdir air_installer_tmp && cd air_installer_tmp
   - wget https://github.com/kwikius/air_installer.zip
   - unzip air_installer.zip
   - make clean && make CXX="g++-4.8"
   - mkdir $HOME/ap_lib
   - mkdir $HOME/ap_bin
   - make execute
   - cd ../
   
script:  ls $HOME/ap_lib && ls $HOME/ap_bin